export const LOAD_SUBSCRIPTIONS_SUCCESS = 'LOAD_SUBSCRIPTIONS_SUCCESS';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION'; 

export const ROUTE_LOGIN = 'ROUTE_LOGIN';
export const ROUTE_LOGOUT = 'ROUTE_LOGOUT';
export const ROUTE_MAIN = 'ROUTE_MAIN';
export const ROUTE_PROFILE = 'ROUTE_PROFILE';
