export const LOAD_SUBSCRIPTIONS_SUCCESS = 'LOAD_SUBSCRIPTIONS_SUCCESS';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER'; 

export const ROUTE_LOGIN = 'ROUTE_LOGIN';
export const ROUTE_MAIN = 'ROUTE_MAIN';
export const ROUTE_PROFILE = 'ROUTE_PROFILE';

